### ISSUE TITLE
model help does not fit on my screen

### ISSUE THREAD

**Issue by jaresty** [C-Loftus/talon-ai-tools#4]
When I run `model help`, the dialog box extends off both sides of my screen.

**Comment by C-Loftus** [comment]
Known issue. We need to abbreviate the list somehow visually without actually changing it. Not sure how to do this at the moment, since we are using the built in community help function to display a talon list. Should be easy to write our own help fn though

**Comment by C-Loftus** [comment]
I am wondering if similar to the Cursorless cheatsheet it would be better to have some sort of model cheatsheet in HTML  so it can be viewed in the browser.

**Comment by jaresty** [comment]
That could work. One thought could be to abbreviate the explanations on the existing help page. The commands themselves are pretty self-explanatory. Is hard to remember all the options, though.

**Comment by C-Loftus** [comment]
Yeah, so unfortunately we cannot abbreviate the explanation using the existing Talon list since there is no way to read the values from a Talon list within a context object.

So, there are two options. We can either create another parallel Talon list with the same keys and the values being the documentation string, or we could just have a JSON file. With the latter, we'll have one single file that can be read in with both the prompt and the associated documentation string. However, that ends up being more verbose and not as tightly integrated with talon.

This is not a difficult technical problem, but I'm just thinking about which way will make it easiest for users to understand. 
Honestly I might end up just using a static site generator for a simple docs website, since I don't particularly love the imgui window to begin with. ( they aren't accessible with a screen reader)

**Comment by jaresty** [comment]
It would also be nice to be able to customize the list of commands. I was considering submitting a PR to provide a separate csv or something similar to how some of the other talon settings can live outside of the community repository for customization. This idea might inform your approach here as well.

**Comment by C-Loftus** [comment]
So, I think, in general, the Talon community is moving away from CSVs to .talon-list files. But, that being said, I do agree with what you're saying there. I am finding that there are a lot of more niche prompts that are useful for some people but won't be necessary for most.

Perhaps we will have a series of Talon lists that can be contextually enabled with some sort of tag, and then the help menu will only show the ones which are contextually enabled. I will continue to think about this, though.

**Comment by C-Loftus** [comment]
I changed the help command so that it reads it in and then opens it in the browser. I kind of like this because we don't have to use the inaccessible imgui windows. However, let me know your opinions on this. I didn't really want to abbreviate the prompt since I feel like every part of the prompt is relevant to the expected output the user would want. I can obviously stylize this a bit if it seems useful. I didn't want to do too much at first though in case this doesn't seem like a good solution.

**Comment by jaresty** [comment]
This is awesome! The new output is much easier to read. I'm gonna close this issue.
